# Configuration script to Travis-CI
language: python
python:
  - "3.6"
install:
  - pip install --upgrade -e .[test]
  - pip install coveralls
script:
  - pytest -v --cov src/mypy_zope
  - mypy src --strict
after_success:
  coveralls
